server:
  port: 1005

spring:
  application:
    name: czmall-email

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1002/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

