server:
  port: 1001

spring:
  application:
    name: czmall-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1002/eureka
    fetch-registry: true
    register-with-eureka: true
