server:
  port: 1009

spring:
  application:
    name: czmall-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1002/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
