server:
  port: 1004

spring:
  application:
    name: czmall-goods

  datasource:
    url: jdbc:mysql://localhost:3306/CZ_MALL?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1002/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.czmall.goods.model
